# This is a basic workflow to help you get started with Actions

name: e2e

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_run:
    workflows: [build-auto-tag]
    types:
        - completed
      
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "${{ steps.previoustag.outputs.tag }}"
      
      - name: Run a one-line script
        run: echo "${{github.event.release.tag_name}}"

        
      
      - name: Run a one-line script
        run: echo "${{ github.ref_name }}"
      
      - name: Run a one-line script
        run: echo "${{ github.event.workflow_run.display_title }}"
